import { ProductImages } from "../resources/resource_directories"

export const genderList = [
    { label: "Male", value: "m" },
    { label: "Female", value: "f" },
    { label: "Other", value: "o" }
]; //List for DropDownPicker Component

export const nationList = [
    { label: "Afghanistan", value: "afghanistan" },
    { label: "Albania", value: "albania" },
    { label: "Algeria", value: "algeria" },
    { label: "Andorra", value: "andorra" },
    { label: "Angola", value: "angola" },
    { label: "Antigua and Barbuda", value: "antigua-and-barbuda" },
    { label: "Argentina", value: "argentina" },
    { label: "Armenia", value: "armenia" },
    { label: "Australia", value: "australia" },
    { label: "Austria", value: "austria" },
    { label: "Azerbaijan", value: "azerbaijan" },
    { label: "Bahamas", value: "bahamas" },
    { label: "Bahrain", value: "bahrain" },
    { label: "Bangladesh", value: "bangladesh" },
    { label: "Barbados", value: "barbados" },
    { label: "Belarus", value: "belarus" },
    { label: "Belgium", value: "belgium" },
    { label: "Belize", value: "belize" },
    { label: "Benin", value: "benin" },
    { label: "Bhutan", value: "bhutan" },
    { label: "Bolivia", value: "bolivia" },
    { label: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
    { label: "Botswana", value: "botswana" },
    { label: "Brazil", value: "brazil" },
    { label: "Brunei", value: "brunei" },
    { label: "Bulgaria", value: "bulgaria" },
    { label: "Burkina Faso", value: "burkina-faso" },
    { label: "Burundi", value: "burundi" },
    { label: "Cabo Verde", value: "cabo-verde" },
    { label: "Cambodia", value: "cambodia" },
    { label: "Cameroon", value: "cameroon" },
    { label: "Canada", value: "canada" },
    { label: "Central African Republic", value: "central-african-republic" },
    { label: "Chad", value: "chad" },
    { label: "Chile", value: "chile" },
    { label: "China", value: "china" },
    { label: "Colombia", value: "colombia" },
    { label: "Comoros", value: "comoros" },
    { label: "Democratic Republic of the Congo", value: "democratic-republic-of-the-congo" },
    { label: "Republic of the Congo", value: "republic-of-the-congo" },
    { label: "Costa Rica", value: "costa-rica" },
    { label: "Côte d’Ivoire", value: "côte-d’ivoire" },
    { label: "Croatia", value: "croatia" },
    { label: "Cuba", value: "cuba" },
    { label: "Cyprus", value: "cyprus" },
    { label: "Czech Republic", value: "czech-republic" },
    { label: "Denmark", value: "denmark" },
    { label: "Djibouti", value: "djibouti" },
    { label: "Dominica", value: "dominica" },
    { label: "Dominican Republic", value: "dominican-republic" },
    { label: "East Timor", value: "east-timor" },
    { label: "Ecuador", value: "ecuador" },
    { label: "Egypt", value: "egypt" },
    { label: "El Salvador", value: "el-salvador" },
    { label: "Equatorial Guinea", value: "equatorial-guinea" },
    { label: "Eritrea", value: "eritrea" },
    { label: "Estonia", value: "estonia" },
    { label: "Eswatini", value: "eswatini" },
    { label: "Ethiopia", value: "ethiopia" },
    { label: "Fiji", value: "fiji" },
    { label: "Finland", value: "finland" },
    { label: "France", value: "france" },
    { label: "Gabon", value: "gabon" },
    { label: "The Gambia", value: "the-gambia" },
    { label: "Georgia", value: "georgia" },
    { label: "Germany", value: "germany" },
    { label: "Ghana", value: "ghana" },
    { label: "Greece", value: "greece" },
    { label: "Grenada", value: "grenada" },
    { label: "Guatemala", value: "guatemala" },
    { label: "Guinea", value: "guinea" },
    { label: "Guinea-Bissau", value: "guinea-bissau" },
    { label: "Guyana", value: "guyana" },
    { label: "Haiti", value: "haiti" },
    { label: "Honduras", value: "honduras" },
    { label: "Hungary", value: "hungary" },
    { label: "Iceland", value: "iceland" },
    { label: "India", value: "india" },
    { label: "Indonesia", value: "indonesia" },
    { label: "Iran", value: "iran" },
    { label: "Iraq", value: "iraq" },
    { label: "Ireland", value: "ireland" },
    { label: "Israel", value: "israel" },
    { label: "Italy", value: "italy" },
    { label: "Jamaica", value: "jamaica" },
    { label: "Japan", value: "japan" },
    { label: "Jordan", value: "jordan" },
    { label: "Kazakhstan", value: "kazakhstan" },
    { label: "Kenya", value: "kenya" },
    { label: "Kiribati", value: "kiribati" },
    { label: "North Korea", value: "north-korea" },
    { label: "South Korea", value: "south-korea" },
    { label: "Kosovo", value: "kosovo" },
    { label: "Kuwait", value: "kuwait" },
    { label: "Kyrgyzstan", value: "kyrgyzstan" },
    { label: "Laos", value: "laos" },
    { label: "Latvia", value: "latvia" },
    { label: "Lebanon", value: "lebanon" },
    { label: "Lesotho", value: "lesotho" },
    { label: "Liberia", value: "liberia" },
    { label: "Libya", value: "libya" },
    { label: "Liechtenstein", value: "liechtenstein" },
    { label: "Lithuania", value: "lithuania" },
    { label: "Luxembourg", value: "luxembourg" },
    { label: "Madagascar", value: "madagascar" },
    { label: "Malawi", value: "malawi" },
    { label: "Malaysia", value: "malaysia" },
    { label: "Maldives", value: "maldives" },
    { label: "Mali", value: "mali" },
    { label: "Malta", value: "malta" },
    { label: "Marshall Islands", value: "marshall-islands" },
    { label: "Mauritania", value: "mauritania" },
    { label: "Mauritius", value: "mauritius" },
    { label: "Mexico", value: "mexico" },
    { label: "Federated States of Micronesia", value: "federated-states-of-micronesia" },
    { label: "Moldova", value: "moldova" },
    { label: "Monaco", value: "monaco" },
    { label: "Mongolia", value: "mongolia" },
    { label: "Montenegro", value: "montenegro" },
    { label: "Morocco", value: "morocco" },
    { label: "Mozambique", value: "mozambique" },
    { label: "Myanmar", value: "myanmar" },
    { label: "Namibia", value: "namibia" },
    { label: "Nauru", value: "nauru" },
    { label: "Nepal", value: "nepal" },
    { label: "Netherlands", value: "netherlands" },
    { label: "New Zealand", value: "new-zealand" },
    { label: "Nicaragua", value: "nicaragua" },
    { label: "Niger", value: "niger" },
    { label: "Nigeria", value: "nigeria" },
    { label: "North Macedonia", value: "north-macedonia" },
    { label: "Norway", value: "norway" },
    { label: "Oman", value: "oman" }, { label: "Pakistan", value: "pakistan" },
    { label: "Palau", value: "palau" },
    { label: "Panama", value: "panama" },
    { label: "Papua New Guinea", value: "papua-new-guinea" },
    { label: "Paraguay", value: "paraguay" },
    { label: "Peru", value: "peru" },
    { label: "Philippines", value: "philippines" },
    { label: "Poland", value: "poland" },
    { label: "Portugal", value: "portugal" },
    { label: "Qatar", value: "qatar" },
    { label: "Romania", value: "romania" },
    { label: "Russia", value: "russia" },
    { label: "Rwanda", value: "rwanda" },
    { label: "Saint Kitts and Nevis", value: "saint-kitts-and-nevis" },
    { label: "Saint Lucia", value: "saint-lucia" },
    { label: "Saint Vincent and the Grenadines", value: "saint-vincent-and-the-grenadines" },
    { label: "Samoa", value: "samoa" },
    { label: "San Marino", value: "san-marino" },
    { label: "Sao Tome and Principe", value: "sao-tome-and-principe" },
    { label: "Saudi Arabia", value: "saudi-arabia" },
    { label: "Senegal", value: "senegal" },
    { label: "Serbia", value: "serbia" },
    { label: "Seychelles", value: "seychelles" },
    { label: "Sierra Leone", value: "sierra-leone" },
    { label: "Singapore", value: "singapore" },
    { label: "Slovakia", value: "slovakia" },
    { label: "Slovenia", value: "slovenia" },
    { label: "Solomon Islands", value: "solomon-islands" },
    { label: "Somalia", value: "somalia" },
    { label: "South Africa", value: "south-africa" },
    { label: "Spain", value: "spain" },
    { label: "Sri Lanka", value: "sri-lanka" },
    { label: "Sudan", value: "sudan" },
    { label: "South Sudan", value: "south-sudan" },
    { label: "Suriname", value: "suriname" },
    { label: "Sweden", value: "sweden" },
    { label: "Switzerland", value: "switzerland" },
    { label: "Syria", value: "syria" },
    { label: "Taiwan", value: "taiwan" },
    { label: "Tajikistan", value: "tajikistan" },
    { label: "Tanzania", value: "tanzania" },
    { label: "Thailand", value: "thailand" },
    { label: "Togo", value: "togo" },
    { label: "Tonga", value: "tonga" },
    { label: "Trinidad and Tobago", value: "trinidad-and-tobago" },
    { label: "Tunisia", value: "tunisia" },
    { label: "Turkey", value: "turkey" },
    { label: "Turkmenistan", value: "turkmenistan" },
    { label: "Tuvalu", value: "tuvalu" },
    { label: "Uganda", value: "uganda" },
    { label: "Ukraine", value: "ukraine" },
    { label: "United Arab Emirates", value: "united-arab-emirates" },
    { label: "United Kingdom", value: "united-kingdom" },
    { label: "United States", value: "united-states" },
    { label: "Uruguay", value: "uruguay" },
    { label: "Uzbekistan", value: "uzbekistan" },
    { label: "Vanuatu", value: "vanuatu" },
    { label: "Vatican City", value: "vatican-city" },
    { label: "Venezuela", value: "venezuela" },
    { label: "Vietnam", value: "vietnam" },
    { label: "Yemen", value: "yemen" },
    { label: "Zambia", value: "zambia" },
    { label: "Zimbabwe", value: "zimbabwe" }
]; //List for DropDownPicker Component

export const productList = [
    { id: 1, name: "CPU Intel Core i7 12700", price: "319$", image: ProductImages.cpu_intel_core_i7_12700 },
    { id: 2, name: "CPU AMD Ryzen 5 5600", price: "117$", image: ProductImages.cpu_amd_ryzen_5_5600 },
    { id: 3, name: "CPU AMD Ryzen 9 9950x", price: "594$", image: ProductImages.cpu_amd_ryzen_9_9950x },
    { id: 4, name: "RAM Corsair Dominator Platinum RGB DDR5 5200MHz 32GB", price: "126$", image: ProductImages.ram_corsair_dominator_platinum_rgb_ddr5_5200mhz_32gb },
    { id: 5, name: "RAM Corsair Vengeance RGB RS DDR4 3200MHz 32GB", price: "78$", image: ProductImages.ram_corsair_vengeance_rgb_rs_ddr4_3200mhz_32gb },
    { id: 6, name: "RAM Corsair Vengeance RGB RS DDR4 3600mhz 8GB", price: "27$", image: ProductImages.ram_corsair_vengeance_rgb_rs_ddr4_3600mhz_8gb },
    { id: 7, name: "RAM Laptop Lexar DDR4 CL22 3200MHz 8GB", price: "17$", image: ProductImages.ram_laptop_lexar_cl22_ddr4_3200mhz_8gb },
    { id: 8, name: "RAM PNY XLR8 Heatsink RGB DDR4 3200MHz 16GB", price: "27$", image: ProductImages.ram_pny_xlr8_heatsink_rgb_ddr4_3200mhz_16gb },
    { id: 9, name: "VGA Asrock AMD Radeon RX 6600 Challenger D 8GB", price: "189$", image: ProductImages.vga_asrock_amd_radeon_rx_6600_challenger_d_8gb },
    { id: 10, name: "VGA ASUS Phoenix GT 1030 OC Edition GDDR5 2GB", price: "112$", image: ProductImages.vga_asus_phoenix_gt_1030_oc_edition_gddr5_2gb },
    { id: 11, name: "VGA ASUS ROG Strix RTX 4090 BTF OC Edition GDDR6X 24GB", price: "2659$", image: ProductImages.vga_asus_rog_strix_rtx_4090_btf_oc_edition_gddr6x_24gb },
    { id: 12, name: "VGA Gigabyte Geforce RTX 4060 Windforce OC 8G", price: "299$", image: ProductImages.vga_gigabyte_geforce_rtx_4060_windforce_oc_8g },
    { id: 13, name: "VGA MSI Geforce GTX 1650 D6 Ventus XS OCV3 4GB", price: "149$", image: ProductImages.vga_msi_geforce_gtx_1650_d6_ventus_xs_ocv3_4gb }
]; //List of demo values